

CREATE SEQUENCE S_USERS;

CREATE SEQUENCE S_GROUPS;

CREATE SEQUENCE S_USER_GROUP_ID;

CREATE SEQUENCE S_FOODS;

CREATE SEQUENCE S_ORDERS;

CREATE TABLE USERS(
    ID          NUMBER NOT NULL,
    NAME        VARCHAR2(50) NOT NULL,
    PASSWORD    VARCHAR2(100),
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_USER_NAME ON USERS(NAME);

CREATE TABLE GROUPS(
    ID          NUMBER NOT NULL,
    NAME        VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    CONSTRAINT PK_GROUPS PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_GROUP_NAME ON GROUPS(NAME);

CREATE TABLE USER_GROUPS(
    USER_ID     NUMBER NOT NULL,
    GROUP_ID    NUMBER NOT NULL,
    CONSTRAINT USER_GROUPS PRIMARY KEY (USER_ID, GROUP_ID)
);

ALTER TABLE USER_GROUPS ADD CONSTRAINT FK_USER_GROUPS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE USER_GROUPS ADD CONSTRAINT FK_USER_GROUPS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID);

CREATE VIEW W_USER_GROUPS (USER_NAME, GROUP_NAME) AS SELECT u.NAME, g.NAME FROM USER_GROUPS ug INNER JOIN USERS u ON ug.USER_ID=u.ID INNER JOIN GROUPS g ON ug.GROUP_ID=g.ID;

CREATE TABLE FOODS(
    ID            NUMBER NOT NULL,
    NAME          VARCHAR2(100) NULL,
    PRICE         DOUBLE PRECISION NOT NULL,
    DELIVERY_DATE  DATE NOT NULL,
    CONSTRAINT PK_FOODSS PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_FOOD_NAME ON FOODS(NAME, DELIVERY_DATE);

CREATE TABLE ORDERS(
    ID          NUMBER NOT NULL,
    USER_ID     NUMBER NOT NULL,
    FOOD_ID     NUMBER NOT NULL,
    QUANTITY    NUMBER(2) NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ID)
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_FOOD FOREIGN KEY (FOOD_ID) REFERENCES FOODS(ID);

CREATE UNIQUE INDEX IDX_ORDERS ON ORDERS(USER_ID, FOOD_ID);
