INSERT INTO USERS(ID, NAME, PASSWORD) VALUES (S_USERS.NEXTVAL, 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');
INSERT INTO USERS(ID, NAME, PASSWORD) VALUES (S_USERS.NEXTVAL, 'user', '04f8996da763b7a969b1028ee3007569eaf3a635486ddab211d512c85b9df8fb');
INSERT INTO USERS(ID, NAME, PASSWORD) VALUES (S_USERS.NEXTVAL, 'quest', 'ac1a1c7143cb2199eb400993a5db42bc2f6d98f6769bb696d04b48d84c68a56f');

INSERT INTO GROUPS(ID, NAME, DESCRIPTION) VALUES (S_GROUPS.NEXTVAL, 'admins', 'admin');
INSERT INTO GROUPS(ID, NAME, DESCRIPTION) VALUES (S_GROUPS.NEXTVAL, 'users', 'users');
INSERT INTO GROUPS(ID, NAME, DESCRIPTION) VALUES (S_GROUPS.NEXTVAL, 'quests', 'quests');

INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM GROUPS WHERE NAME='admins'));
INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='user'), (SELECT ID FROM GROUPS WHERE NAME='users'));
INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='quest'), (SELECT ID FROM GROUPS WHERE NAME='quests'));

INSERT INTO FOODS(ID, NAME, PRICE, DELIVERY_DATE) VALUES (S_FOODS.NEXTVAL, 'Supa crema de legume', 5.5, to_date('2014-01-27', 'yyyy-mm-dd'));
INSERT INTO FOODS(ID, NAME, PRICE, DELIVERY_DATE) VALUES (S_FOODS.NEXTVAL, 'Piept pui la gratar', 5.0, to_date('2014-01-27', 'yyyy-mm-dd'));
INSERT INTO FOODS(ID, NAME, PRICE, DELIVERY_DATE) VALUES (S_FOODS.NEXTVAL, 'Orez', 4.5, to_date('2014-01-27', 'yyyy-mm-dd'));

INSERT INTO ORDERS(ID, USER_ID, FOOD_ID, QUANTITY) VALUES (S_ORDERS.NEXTVAL, (SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM FOODS WHERE NAME='Supa crema de legume' AND DELIVERY_DATE=to_date('2014-01-27', 'yyyy-mm-dd')), 1);
INSERT INTO ORDERS(ID, USER_ID, FOOD_ID, QUANTITY) VALUES (S_ORDERS.NEXTVAL, (SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM FOODS WHERE NAME='Piept pui la gratar' AND DELIVERY_DATE=to_date('2014-01-27', 'yyyy-mm-dd')), 1);
INSERT INTO ORDERS(ID, USER_ID, FOOD_ID, QUANTITY) VALUES (S_ORDERS.NEXTVAL, (SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM FOODS WHERE NAME='Orez' AND DELIVERY_DATE=to_date('2014-01-27', 'yyyy-mm-dd')), 1);
INSERT INTO ORDERS(ID, USER_ID, FOOD_ID, QUANTITY) VALUES (S_ORDERS.NEXTVAL, (SELECT ID FROM USERS WHERE NAME='user'), (SELECT ID FROM FOODS WHERE NAME='Supa crema de legume' AND DELIVERY_DATE=to_date('2014-01-27', 'yyyy-mm-dd')), 1);
