DROP VIEW W_USER_GROUPS;

DROP TABLE ORDERS CASCADE CONSTRAINTS PURGE;

DROP TABLE FOODS CASCADE CONSTRAINTS PURGE;

DROP TABLE USER_GROUPS CASCADE CONSTRAINTS PURGE;

DROP TABLE USERS CASCADE CONSTRAINTS PURGE;

DROP TABLE GROUPS CASCADE CONSTRAINTS PURGE;
