INSERT INTO USERS(NAME, PASSWORD) VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');
INSERT INTO USERS(NAME, PASSWORD) VALUES ('user', '04f8996da763b7a969b1028ee3007569eaf3a635486ddab211d512c85b9df8fb');
INSERT INTO USERS(NAME, PASSWORD) VALUES ('quest', 'ac1a1c7143cb2199eb400993a5db42bc2f6d98f6769bb696d04b48d84c68a56f');

INSERT INTO GROUPS(NAME, DESCRIPTION) VALUES ('admins', 'admin');
INSERT INTO GROUPS(NAME, DESCRIPTION) VALUES ('users', 'users');
INSERT INTO GROUPS(NAME, DESCRIPTION) VALUES ('quests', 'quests');

INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM GROUPS WHERE NAME='admins'));
INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='user'), (SELECT ID FROM GROUPS WHERE NAME='users'));
INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='quest'), (SELECT ID FROM GROUPS WHERE NAME='quests'));

INSERT INTO FOODS(NAME, PRICE, DELIVERY_DATE) VALUES ('Supa crema de legume', 5.5, '2014-01-27');
INSERT INTO FOODS(NAME, PRICE, DELIVERY_DATE) VALUES ('Piept pui la gratar', 5.0, '2014-01-27');
INSERT INTO FOODS(NAME, PRICE, DELIVERY_DATE) VALUES ('Orez', 4.5, '2014-01-27');

INSERT INTO ORDERS(USER_ID, FOOD_ID, QUANTITY) VALUES ((SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM FOODS WHERE NAME='Supa crema de legume' AND DELIVERY_DATE='2014-01-27'), 1);
INSERT INTO ORDERS(USER_ID, FOOD_ID, QUANTITY) VALUES ((SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM FOODS WHERE NAME='Piept pui la gratar' AND DELIVERY_DATE='2014-01-27'), 1);
INSERT INTO ORDERS(USER_ID, FOOD_ID, QUANTITY) VALUES ((SELECT ID FROM USERS WHERE NAME='admin'), (SELECT ID FROM FOODS WHERE NAME='Orez' AND DELIVERY_DATE='2014-01-27'), 1);
INSERT INTO ORDERS(USER_ID, FOOD_ID, QUANTITY) VALUES ((SELECT ID FROM USERS WHERE NAME='user'), (SELECT ID FROM FOODS WHERE NAME='Supa crema de legume' AND DELIVERY_DATE='2014-01-27'), 1);


